spring.application.name=atencion
server.port=8080

sprig.datasource.url=jdbc:h2:file:./data/hospital
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
sprig.datasource.password=org.hibernate.dialect.H2Dialect


spring.h2.consele.enabled=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=ture                                                                       